---
version: "3"
services:
  assembly:
    build:
      context: assembly/
    volumes:
      - share:/opt/App42PaaS-Java-MySQL-Sample/target/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  production:
    image: tomcat:jre8-alpine
    links: 
        - db:db
    volumes:
      - share:/usr/local/tomcat/webapps/
    ports:
       - "8080:8080"
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: 123456
        MYSQL_ROOT_PASSWORD: 123456
    depends_on:
      - assembly
      - db
volumes:
  share:
  my-db: