---
version: "3"
services:
  assembly:
    build:
      context: assembly/
    volumes:
      - share:/opt/App42PaaS-Java-MySQL-Sample/target/
      - config:/opt/App42PaaS-Java-MySQL-Sample/src/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      back:
        ipv4_address: 172.16.238.2
      default:

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456

  production:
#    image: tomcat:jre8-alpine
    build:
      context: production/    
    links: 
        - db:db
    volumes:
      - share:/opt/apache-tomcat-9.0.65/webapps/
      - config:/opt/apache-tomcat-9.0.65/webapps/ROOT/

#      - share:/usr/local/tomcat/webapps/
    ports:
       - "8080:8080"
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: 123456
        MYSQL_ROOT_PASSWORD: 123456
    networks:
      back:
        ipv4_address: 172.16.238.3
      default:
    depends_on:
      - assembly
      - db
volumes:
  share:
  config:
  my-db:

networks:
#Internal-only network for proper nginx proxying and ssh
  back:
    driver: bridge
    enable_ipv6: true
    internal: true
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
       - subnet: 2001:3984:3989::/64 
#External network actually
  default:
    driver: bridge