FROM ubuntu:20.04
RUN apt update
RUN apt install -y default-jdk
RUN apt install -y git
RUN apt install -y maven
WORKDIR /opt/share
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
RUN cd boxfuse-sample-java-war-hello && mvn package
RUN cd boxfuse-sample-java-war-hello && cd target && cp hello-1.0.war /opt/share
VOLUME [ "/boxfuse-sample-java-war-hello/target/hello-1.0.war" ]
CMD ["bash"]